[tool.django-stubs]
django_settings_module = "project.settings"


[tool.isort]
force_single_line = true
line_length = 88
multi_line_output = 3
no_sections = true
py_version = 311


[tool.mypy]
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
exclude = ["migrations", "venv", ".env"]
no_implicit_optional = true
plugins = ["mypy_django_plugin.main", "pydantic.mypy"]
pretty = true
python_version = "3.11"
show_error_context = true
sqlite_cache = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true


[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true


[tool.ruff]
exclude = [".git", "venv", ".venv"]
indent-width = 4
line-length = 88
target-version = "py311"


[tool.ruff.format]
docstring-code-format = false
indent-style = "space"
line-ending = "auto"
quote-style = "double"
skip-magic-trailing-comma = false

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "COM812",
    "D",
    "F401",
    "FIX002",
    "I001",
    "ISC001",
    "PT009",
    "RET504",
    "TD003",
]
