# Generated by Django 5.0.7 on 2024-07-31 13:16

from django.db import migrations
from django.db import models
from typing import ClassVar


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar = []

    operations: ClassVar = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(unique=True)),
                ("content", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
